[main]
default_printer: Micron

[printer Micron]
titlebar_items: extruder,heater_bed,chamber

[menu __main favourites]
name: {{ gettext('Favourites') }}
icon: custom-script

[menu __main favourites clean_nozzle]
name: {{ gettext('Clean nozzle') }}
icon: extruder
enable: {{ printer.extruders.count > 0 }}
method: printer.gcode.script
params: {"script":"CLEAN_NOZZLE_AND_PARK"}

[menu __main favourites toolhead_park]
name: {{ gettext('Park toolhead') }}
icon: stop
method: printer.gcode.script
params: {"script":"TOOLHEAD_PARK"}

[menu __main favourites goto_center]
name: {{ gettext('Goto center') }}
icon: move
method: printer.gcode.script
params: {"script":"GOTO_CENTER"}

[menu __main favourites level_bed]
name: {{ gettext('Level bed') }}
icon: bed-level
method: printer.gcode.script
params: {"script":"LEVEL_BED"}

[menu __main favourites toggle_filtration]
name: {{ gettext('Toggle Air Filtration') }}
icon: fan-on
method: printer.gcode.script
params: {"script":"TOGGLE_FILTRATION"}

[menu __main favourites toggle_recirculation]
name: {{ gettext('Toggle Air Recirculation') }}
icon: shuffle
method: printer.gcode.script
params: {"script":"TOGGLE_RECIRCULATION"}

[menu __main favourites chamber_togle_led]
name: {{ gettext('Toggle LED') }}
icon: light
method: printer.gcode.script
params: {"script":"CHAMBER_LED_STATIC_TOGGLE"}

[menu __main favourites shutdown_printer]
name: {{ gettext('Power off') }}
icon: shutdown
method: printer.gcode.script
params: {"script":"SHUTDOWN"}

[preheat cooldown]
heater_bed: 0
extruder: 0

[preheat TAP]
extruder: 150

[preheat ABS]
heater_bed: 105
extruder: 250
gcode:
   SET_FAN_SPEED FAN=filter SPEED=1.0
   SET_FAN_SPEED FAN=chamber SPEED=1.0

[preheat PC]
heater_bed: 105
extruder: 285
gcode:
   SET_FAN_SPEED FAN=filter SPEED=1.0
   SET_FAN_SPEED FAN=chamber SPEED=1.0

[preheat PETG]
heater_bed: 90
extruder: 240

[preheat PLA]
heater_bed: 60
extruder: 210

[preheat WOOD]
heater_bed: 70
extruder: 190

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = material-darker
#~# side_macro_shortcut = True
#~# font_size = large
#~# move_speed_xy = 300
#~# print_sort_dir = date_desc
#~# print_view = list
#~# 
#~# [displayed_macros Micron]
#~# compute_mesh_parameters = False
#~# t0 = False
#~# print_start = False
#~# print_end = False
#~# m572 = False
#~# adaptive_bed_mesh = False
#~# adaptive_line_purge = False
#~# clean_nozzle = False
#~# set_logo_leds_off = False
#~# set_nozzle_leds_off = False
#~# set_logo_leds_on = False
#~# set_nozzle_leds_on = False
#~# status_busy = False
#~# status_calibrating_z = False
#~# status_cleaning = False
#~# status_cooling = False
#~# status_homing = False
#~# status_heating = False
#~# status_printing = False
#~# status_leveling = False
#~# status_part_ready = False
#~# 
#~# [graph Micron]
#~# temperature_fan pi_fan = False
#~# temperature_fan mcu_fan = False
#~# temperature_sensor gbb15 = False
#~# temperature_sensor ebb36 = False
#~# temperature_sensor extruder_stepper = False
#~# 
#~# [spoolman]
#~# hide_archived = False
#~#
